version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build -t telegram-proxy .
          no_output_timeout: 30m
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag telegram-proxy $DOCKER_USER/telegram-proxy:latest
            docker push $DOCKER_USER/telegram-proxy:latest
