version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/telegram-proxy.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/telegram-proxy.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build -t telegram-proxy .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/telegram-proxy.tar telegram-proxy
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/telegram-proxy.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag telegram-proxy $DOCKER_USER/telegram-proxy:latest
            docker push $DOCKER_USER/telegram-proxy:latest
